# Generated by Django 4.2.1 on 2023-06-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0007_alter_classgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cycle', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.cycle')),
                ('field', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.field')),
                ('level', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
            ],
        ),
    ]
