# Generated by Django 4.2.1 on 2023-06-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_subject_classtimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimeslot',
            name='day',
            field=models.CharField(blank=True, choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], max_length=3, null=True),
        ),
    ]
