# Generated by Django 4.2.1 on 2023-06-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_classtimeslot_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='timetable_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='classtimeslot',
            name='day',
            field=models.CharField(blank=True, choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], max_length=3, null=True),
        ),
    ]
