# Generated by Django 4.2.1 on 2023-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_alter_classtimetable_timetable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='semester',
            field=models.CharField(blank=True, choices=[('S1', 'SEMESTER 1'), ('S2', 'SEMESTER 2'), ('S3', 'SEMESTER 3'), ('S4', 'SEMESTER 4'), ('S5', 'SEMESTER 5'), ('S6', 'SEMESTER 6'), ('S7', 'SEMESTER 7'), ('S8', 'SEMESTER 8'), ('S9', 'SEMESTER 9'), ('S10', 'SEMESTER 10')], max_length=3, null=True),
        ),
    ]
