# Generated by Django 4.2.1 on 2023-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0006_classtimetable_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='timetable_type',
            field=models.CharField(blank=True, choices=[('TD', 'TD'), ('Exam', 'Exam'), ('Class', 'Class'), ('TP', 'TP'), ('General', 'General')], max_length=8, null=True),
        ),
    ]
