# Generated by Django 4.2.1 on 2023-06-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_alter_classgroup_options'),
        ('timetables', '0008_alter_classtimeslot_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimeslot',
            name='class_groups',
            field=models.ManyToManyField(blank=True, null=True, to='levels.classgroup'),
        ),
    ]
