# Generated by Django 4.2.1 on 2023-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0009_classtimeslot_class_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimetable',
            name='timetable_type',
        ),
        migrations.AddField(
            model_name='classtimeslot',
            name='slot_type',
            field=models.CharField(blank=True, choices=[('TD', 'TD'), ('Exam', 'Exam'), ('Class', 'Class'), ('TP', 'TP'), ('General', 'General')], max_length=8, null=True),
        ),
    ]
