# Generated by Django 4.2.1 on 2023-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0010_remove_classtimetable_timetable_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='timetable_type',
            field=models.CharField(blank=True, choices=[('TD', 'TD'), ('Exam', 'Exam'), ('Class', 'Class'), ('TP', 'TP'), ('General', 'General')], max_length=8, null=True),
        ),
    ]
