# Generated by Django 4.2.1 on 2023-06-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0011_classtimetable_timetable_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimetable',
            name='timetable_type',
        ),
    ]
