# Generated by Django 4.2.1 on 2023-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0012_remove_classtimetable_timetable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimeslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classtimeslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classtimeslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
