# Generated by Django 4.2.1 on 2023-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0014_remove_classtimeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimeslot',
            name='start_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classtimeslot',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
