# Generated by Django 4.2.1 on 2023-06-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0015_alter_classtimeslot_start_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimeslot',
            name='start_period',
        ),
        migrations.RemoveField(
            model_name='classtimeslot',
            name='total_hours',
        ),
    ]
