# Generated by Django 4.2.1 on 2023-07-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0016_remove_classtimeslot_start_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtimeslot',
            options={'ordering': ['start_time']},
        ),
    ]
