# Generated by Django 4.2 on 2023-06-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_student_mat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_mat',
            new_name='user_mat',
        ),
    ]
