# Generated by Django 4.2 on 2023-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_classgroup'),
        ('users', '0005_studentprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_groups',
            field=models.ManyToManyField(to='levels.classgroup'),
        ),
    ]
