# Generated by Django 4.2 on 2023-06-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_classgroup'),
        ('users', '0007_alter_studentprofile_class_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_groups',
            field=models.ManyToManyField(blank=True, null=True, to='levels.classgroup'),
        ),
    ]
