# Generated by Django 4.2 on 2023-06-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_cycle_level_cycle'),
        ('users', '0008_alter_studentprofile_class_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='field_status',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.cycle'),
        ),
    ]
