# Generated by Django 4.2.1 on 2023-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_studentprofile_field_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='field',
            new_name='cycle',
        ),
    ]
