# Generated by Django 4.2.1 on 2023-06-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_alter_classgroup_options'),
        ('users', '0010_rename_field_studentprofile_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.field'),
        ),
    ]
