# Generated by Django 4.2.1 on 2023-06-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_alter_classgroup_options'),
        ('users', '0012_alter_studentprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_groups',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.classgroup'),
        ),
    ]
