# Generated by Django 4.2 on 2023-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, choices=[('Gen_Course', 'General Course'), ('Eelec_E', 'Electrical Engineering'), ('Comp_E', 'Computer Engineering'), ('Proc_E', 'Process Engineering'), ('Civil_E', 'Civil Engineering'), ('Mecha_E', 'Mechanical Engineering')], default='Gen_Course', max_length=10, null=True)),
                ('level', models.ManyToManyField(to='levels.level')),
            ],
        ),
    ]
