# Generated by Django 4.2 on 2023-06-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_classgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='Cycle',
            field=models.ManyToManyField(blank=True, to='levels.cycle'),
        ),
    ]
