# Generated by Django 4.2 on 2023-06-18 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_cycle_level_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='Cycle',
        ),
        migrations.AddField(
            model_name='level',
            name='Cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.cycle'),
        ),
    ]
