# Generated by Django 4.2 on 2023-06-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_remove_level_cycle_level_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='Cycle',
            new_name='cycle',
        ),
    ]
