# Generated by Django 4.2.1 on 2023-06-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_rename_cycle_level_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='level',
            new_name='levels',
        ),
    ]
