# Generated by Django 4.2.1 on 2023-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_rename_level_field_levels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['level', 'name']},
        ),
    ]
